#!/bin/bash
set -euxo pipefail
exec 2>&1

if [ "$OCFWEB_TESTING" == "1" ]; then
    echo 'Warning! This will probably fail in dev!'
fi

exec /usr/bin/spiped \
    -e -D -g -F -k /etc/ocfweb/create-redis.key \
    -p /dev/null \
    -s 127.0.0.1:6378 \
    -t create:6379
